// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfudtytaljeexrktgocs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmdWR0eXRhbGplZXhya3Rnb2NzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMDI4OTUsImV4cCI6MjA1ODY3ODg5NX0.mptEH8En2nsHvQ477fPWHhTmwv8GpGvem1Vm8TC76Z0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);